name: Metrics
on:
  schedule: [{cron: "0 * * * *"}] # Update every hour
  workflow_dispatch:

permissions:
  contents: write # Grants the token WRITE access to the repository contents
  # Add other permissions if needed, e.g., issues: write, pull-requests: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # ✨ Row 1: Base profile info (full width)
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata

      # ✨ Row 2: Languages + Contributions calendar
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.row2.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 6

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.row2.calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      # ✨ Row 3: AniList + Achievements
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.row3.anilist.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_anilist: yes
          plugin_anilist_favorites_characters: yes
          plugin_anilist_favorites_manga: yes
          plugin_anilist_user: MahekScripts
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.row3.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 6
