name: Generate Metrics

on:
  schedule: [{cron: "0 0 * * *"}] # Runs once every day at midnight
  workflow_dispatch:              # Allows manual trigger

permissions:
  contents: write # Grants the token WRITE access to the repository contents
  # Add other permissions if needed, e.g., issues: write, pull-requests: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_achievements: yes
          plugin_stars: yes
          config_timezone: Asia/Kolkata
