name: Metrics
on:
  schedule: [{cron: "0 * * * *"}] # Update every hour
  workflow_dispatch:

permissions:
  contents: write # Grants the token WRITE access to the repository contents
  # Add other permissions if needed, e.g., issues: write, pull-requests: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # ✨ Row 1: Base profile info (full width)
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata

      # ✨ Row 2: Languages + Contributions calendar
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.row2.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 6

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.row2.calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      # ✨ Row 3: AniList + Achievements
      - name: Favorites anime and currently watching
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.anilist.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: MahekScripts
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 4

      - name: Favorites characters
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.anilist.characters.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: MahekScripts
          plugin_anilist_sections: characters
          plugin_anilist_limit_characters: 22

          
      # ✨ repo
      - name: Example
        uses: lowlighter/metrics@latest
        with:
          template: repository
          filename: metrics.repository.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Dev-Mahek
          repo: javascriptDOM-playground
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes

      # activity
      - name: Recent activity
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create

      # followeras
      - name: Followers
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.people.followers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_people: yes
          plugin_people_types: followers
